spring:
  profiles:
    active: local
  config:
    import: classpath:application-secret.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  access-token-validity-in-seconds: 1209600
  refresh-token-validity-in-seconds: 1209600

oauth2:
  kakao:
    token-uri: "https://kauth.kakao.com/oauth/token"
    user-info-uri: "https://kapi.kakao.com/v2/user/me"